services:
  jetson-builder:
    build:
      context: ../..
      dockerfile: homie_os/docker/Dockerfile.jetson-builder
      platforms:
        - linux/arm64
      args:
        VERSION: ${HOMIE_VERSION:-dev}
        BUILD_DATE: ${BUILD_DATE}
        HOMIE_BRANCH: ${HOMIE_BRANCH:-main}
        CUDA_VERSION: ${CUDA_VERSION:-12.2}
        TENSORRT_VERSION: ${TENSORRT_VERSION:-10.0}
        JETPACK_VERSION: ${JETPACK_VERSION:-6.0}
        L4T_VERSION: ${L4T_VERSION:-r36.2.0}
        TARGET_ARCHITECTURE: ${TARGET_ARCHITECTURE:-arm64}
        CONTAINER_TIMEZONE: ${CONTAINER_TIMEZONE:-UTC}
        DEBIAN_FRONTEND: ${DEBIAN_FRONTEND:-noninteractive}
    image: homie-os:jetson-${HOMIE_VERSION:-dev}
    container_name: homie-jetson-builder
    privileged: true
    volumes:
      # Mount build output directory
      - ./build:/build
      # Mount source directories for copying
      - ../homie_orchestrator:/src/homie_orchestrator:ro
      - ../config:/src/config:ro
      - ../scripts:/src/scripts:ro
      # Mount Docker socket for container builds
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - HOMIE_VERSION=${HOMIE_VERSION:-dev}
      - BUILD_DATE=${BUILD_DATE}
      - HOMIE_BRANCH=${HOMIE_BRANCH:-main}
      - CUDA_VERSION=${CUDA_VERSION:-12.2}
      - TENSORRT_VERSION=${TENSORRT_VERSION:-10.0}
      - JETPACK_VERSION=${JETPACK_VERSION:-6.0}
      - L4T_VERSION=${L4T_VERSION:-r36.2.0}
      - TARGET_ARCHITECTURE=${TARGET_ARCHITECTURE:-arm64}
      - RAUC_KEY_PATH=/build/certs/rauc-key.pem
      - RAUC_CERT_PATH=/build/certs/rauc-cert.pem
    networks:
      - homie-build

  # Extract rootfs from built image
  rootfs-extractor:
    image: homie-os:jetson-${HOMIE_VERSION:-dev}
    container_name: homie-rootfs-extractor
    command: /bin/bash -c "echo 'Container ready for rootfs extraction'"
    volumes:
      - ./build:/build
    networks:
      - homie-build
    depends_on:
      - jetson-builder

  # Bundle creator service
  bundle-creator:
    image: alpine:latest
    container_name: homie-bundle-creator
    working_dir: /work
    volumes:
      - ./build:/work/build
      - ../scripts:/work/scripts:ro
      - ./bundle:/work/bundle
    environment:
      - HOMIE_VERSION=${HOMIE_VERSION:-dev}
      - RAUC_KEY_PATH=/work/build/certs/rauc-key.pem
      - RAUC_CERT_PATH=/work/build/certs/rauc-cert.pem
    command: /bin/sh -c "apk add --no-cache rauc openssl && /work/scripts/create-docker-bundle.sh"
    networks:
      - homie-build
    depends_on:
      - rootfs-extractor

networks:
  homie-build:
    driver: bridge

volumes:
  build-cache:
    driver: local
